[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Roger-luo", email = "rogerluo.rl18@gmail.com"},
]
dependencies = [
    "numpy>=1.24.2",
    "requests==2.28.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}
